<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>60d8f43c-4bc9-47f6-9e51-b14348305ccc</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1"/>
        <PackageReference Include="AspNetCore.HealthChecks.Elasticsearch" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Hangfire" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0"/>
        <PackageReference Include="Hangfire" Version="1.8.24" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.1"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.12.0-beta.1"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.12.0-beta.1"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0"/>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
        <PackageReference Include="Serilog.Sinks.Http" Version="9.2.0"/>
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
        <ProjectReference Include="..\NotificationService.Cache\NotificationService.Cache.csproj" />
        <ProjectReference Include="..\NotificationService.DAL\NotificationService.DAL.csproj"/>
        <ProjectReference Include="..\NotificationService.Messaging\NotificationService.Messaging.csproj" />
        
    </ItemGroup>

</Project>
